# Site settings

title: Jiayun Fang # Title of your site
name: Jiayun Fang # Title of your site
email: jn.fang@me.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Official website of Jiayun Fang, engineer and feminist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jnfang.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

github_username:      jnfang  # Replace this with your GitHub username
linkedin_username:    jnfang  # Replace this with your LinkedIn username

# Build settings
markdown: kramdown

gems: [rmagick, exifr]


navigation:
- text: About
  url: /index.html
- text: Resume
  title: resume
  url: /resume.html
- text: Projects
  title: projects
  url: /projects/
- text: Travel
  title: travel
  url: /travel/
- text: Photography
  title: photography
  url: /photography/
